include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    sort_child_properties_last: true
    depend_on_referenced_packages: false
    always_use_package_imports: false
    prefer_relative_imports: true

analyzer:
  exclude:
    - '*/generated/**'
    - '**/*.g.dart'
    - '*/example/**'
    - '*/protobuf/**'